### PR TITLE
Resolves #183: pass the transformed list of files to metalsmith.match…

### LINKED ISSUE #183: v2.5.0 breaks integration with metalsmith-watch
The change made in [this commit](https://github.com/metalsmith/layouts/commit/43c781c12980c018cd663e485be31ff4e0cb767a) from using multimatch directly to using metalsmith.match() breaks the integration with metalsmith-watch. The call to metalsmith.match() returns an empty array, which (correctly) triggers the "no files to process" error. Whereas matching against *files* directly correctly populates the matchedFiles variable.

### PR DESCRIPTION
**Pull request by exortech**
… so that renamed files can be matched

https://github.com/metalsmith/layouts/issues/183

### CODE REVIEW

**Comment by webketje** [comment]
@exortech thx, before I merge can you give me a short step-by-step instruction to reproduce the issue. The 'cached' copy of metalsmith files that metalsmith.match uses when you omit the second param, should be a reference to one and the same object.

**Comment by exortech** [comment]
@webketje this is the repo for one of the static sites we build with Metalsmith that was having the issue: https://github.com/doteco/www. If you check out [build.js](https://github.com/doteco/www/blob/master/build.js) you can see the list of plugins used in the build.

It's a bit complicated to produce a simple repro; however, the gist is that, as you noted, metalsmith-watch creates a new file list (containing only the modified files to rebuild) and then invokes [metalsmith.run](https://github.com/FWeinb/metalsmith-watch/blob/master/src/index.es#L121).

I'm not that familiar with the metalsmith codebase, so I can't speak to the best way to fix it. However, while perhaps unmaintained, metalsmith-watch is a really useful plugin. And I imagine that there are potentially other plugins out there that could be doing something similar. To prevent those plugins from breaking, it may be best to preserve the original behaviour - especially as it is a very simple change to ensure that the file list is passed it. It's behaviour that's already supported by the existing interface.

Also, it seems like there's no reason why metalsmith-layouts should assume that the original files list is what is being passed to the plugin. I'm unclear why it's necessary for metalsmith to maintain this state instead of just operating as an immutable, pure function.

**Comment by webketje** [comment]
> [...] it may be best to preserve the original behaviour - especially as it is a very simple change to ensure that the file list is passed it. It's behaviour that's already supported by the existing interface.
> Also, it seems like there's no reason why metalsmith-layouts should assume that the original files list is what is being passed to the plugin. 

I totally agree with you on this.

> I'm unclear why it's necessary for metalsmith to maintain this state instead of just operating as an immutable, pure function.

It is not necessary. The `_files` "cache" was a quick solution to provide a super-easy signature for `metalsmith.match` but the mechanism needs to be made more bullet-proof. The run function should indeed act as an immutable pure function.

**Comment by webketje** [comment]
@exortech Could you help validating an alternative patch to Metalsmith itself works by temporarily replacing `node_modules/metalsmith/lib/index.js` contents with those in the hotfix branch I just pushed here: https://github.com/metalsmith/metalsmith/blob/hotfix/ms-match/lib/index.js?

**Pull request merged**
